# Generated by Django 4.2.30 on 2026-05-09 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Sondage',
        ),
    ]
