# Generated by Django 4.2.30 on 2026-05-09 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_rename_survey_sondage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey',
            new_name='sondage',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='survey',
            new_name='sondage',
        ),
        migrations.AlterField(
            model_name='sondage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to=settings.AUTH_USER_MODEL),
        ),
    ]
